{ config, pkgs, lib, ... }: {
  networking.firewall = { allowedUDPPorts = [ 51820 ]; };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."wireguard" = {
    image = "lscr.io/linuxserver/wireguard:latest";
    environment = {
      "ALLOWEDIPS" = "0.0.0.0/0,::/0";
      "INTERNAL_SUBNET" = "10.13.13.0";
      "LOG_CONFS" = "true";
      "PEERDNS" = "192.168.0.13";
      "PEERS" =
        "starztower,starztab,starzs23,starvpnmark,starzvpnpax,starvpnjune,starz7070,starzvpnlucy,starzvpnbrooke";
      "PERSISTENTKEEPALIVE_PEERS" = "all";
      "PGID" = "1000";
      "PUID" = "1000";
      "SERVERPORT" = "51820";
      "SERVERURL" = "starmaid.xyz";
      "TZ" = "Etc/UTC";
    };
    volumes = [
      "/docker-data/wireguard/config:/config:rw"
      #"/lib/modules:/lib/modules:rw"
    ];
    ports = [ "51820:51820/udp" ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      #"--cap-add=SYS_MODULE"
      #"--network-alias=wireguard"
      #"--network=host"
      "--sysctl=net.ipv4.conf.all.src_valid_mark=1"
      "--sysctl=net.ipv4.ip_forward=1"
      "--sysctl=net.ipv6.conf.all.forwarding=1"
    ];
  };
  systemd.services."docker-wireguard" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [ "docker-compose-wireguard-project-root.target" ];
    wantedBy = [ "docker-compose-wireguard-project-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-wireguard-project-root" = {
    unitConfig = { Description = "Root target generated by compose2nix."; };
    wantedBy = [ "multi-user.target" ];
  };

}
